version: '3.8'

services:
  flask-app: 
    container_name: events_api
    build: ./app
    ports: 
      - "5000:5000"
    env_file:
      - ./app/.env
    restart: always 
    depends_on:
      - db
 
  db:
    container_name: events_db
    image: mysql:8.0.21
    ports:
      - "3306:3306"
    env_file:
      - ./app/.env
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - db:/var/lib/mysql

volumes:
  db: