name: CI/CD

on:
  push:
    branches:
      - main 

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Git-checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4 
        with:
          python-version: '3.10'

      - name: flake8 Lint
        uses: py-actions/flake8@v2

  built_and_push:
    runs-on: ubuntu-latest
    name: Built and push docker image
    needs: Lint
    outputs:
      commit_hash: ${{ steps.commit_hash.outputs.commit_hash }}
    steps:
      - name: Git-checkout
        uses: actions/checkout@v3

      - name: commit_hash 
        run: echo "::set-output name=commit_hash::${GIHUB_SHA::7}"

      - name: Build docker-compose
        run: docker-compose up -d

      

      



