name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: astanil/flask

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Git-checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4 
        with:
          python-version: '3.10'

      - name: flake8 Lint
        uses: py-actions/flake8@v2

  build_and_push:
    runs-on: ubuntu-latest
    name: Build_and_push
    needs: Lint
    outputs:
      commit_hash: ${{ steps.commit_hash.outputs.commit_hash }}
    steps:
      - name: Git-checkout
        uses: actions/checkout@v3

      - name: commit_hash 
        run: echo "::set-output name=commit_hash::${GIHUB_SHA::7}"

      - name: get environment
        run: cp app/.env.example app/.env 

      - name: Docker hub login
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker-compose
        run: docker-compose up -d

      - name: Connect tags
        run: sudo docker tag flask_flask-app:latest astanil/flask:latest  
        
      - name: push
        uses: docker/build-push-action@v3
        with:
          context: ./app
          push: true
          tags: |
            ${{ env.REGISTRY }}:${{ steps.commit_hash.outputs.commit_hash }}
 
  deploy: 
    runs-on: ubuntu-latest
    name: Deploy
    needs: Build_and_push
    env:
      HOST: 3.74.156.7
      USERNAME: ubuntu
    steps:
      - name: Deploy to EC2 instance via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd flask
            sudo docker compose up -d
            